/**
 * AI Symptom Checker - PDF Report Generator
 * 
 * @author Fazilkhan Malek
 * @created 2026
 * @license MIT with Attribution
 * @description Generates downloadable PDF reports from symptom analysis results
 */

import jsPDF from 'jspdf';
import { SymptomAnalysisResult } from '../types/SymptomAnalysisResult';

interface ReportData {
  analysis: SymptomAnalysisResult;
  patientInfo?: {
    age?: string;
    gender?: string;
    allergies?: string;
    chronicConditions?: string;
  };
  symptomDescription: string;
  language: string;
}

const translations = {
  en: {
    title: 'Medical Symptom Analysis Report',
    generatedOn: 'Report Generated On',
    patientInfo: 'Patient Information',
    age: 'Age',
    gender: 'Gender',
    allergies: 'Allergies',
    chronicConditions: 'Chronic Conditions',
    notProvided: 'Not provided',
    symptomDescription: 'Symptom Description',
    analysisResults: 'Analysis Results',
    possibleCondition: 'Possible Condition',
    severity: 'Severity Level',
    symptomsExtracted: 'Extracted Symptoms',
    feelingSummary: 'How You Are Feeling',
    selfCareTips: 'Self-Care Tips',
    recommendedDoctor: 'Recommended Doctor Type',
    nextSteps: 'Next Steps',
    additionalNotes: 'Additional Notes & Warnings',
    disclaimer:
      'DISCLAIMER: This report is generated by an AI assistant and should not replace professional medical advice. Always consult with a qualified healthcare professional for diagnosis and treatment.',
  },
  ar: {
    title: 'تقرير تحليل الأعراض الطبية',
    generatedOn: 'تم إنشاء التقرير في',
    patientInfo: 'معلومات المريض',
    age: 'العمر',
    gender: 'الجنس',
    allergies: 'الحساسية',
    chronicConditions: 'الأمراض المزمنة',
    notProvided: 'لم يتم التقديم',
    symptomDescription: 'وصف الأعراض',
    analysisResults: 'نتائج التحليل',
    possibleCondition: 'الحالة المحتملة',
    severity: 'مستوى الخطورة',
    symptomsExtracted: 'الأعراض المستخرجة',
    feelingSummary: 'ملخص الحالة',
    selfCareTips: 'نصائح الرعاية الذاتية',
    recommendedDoctor: 'نوع الطبيب الموصى به',
    nextSteps: 'الخطوات التالية',
    additionalNotes: 'ملاحظات وتحذيرات إضافية',
    disclaimer:
      'تنويه: تم إنشاء هذا التقرير بواسطة مساعد ذكاء اصطناعي ولا يجب أن يحل محل المشورة الطبية المهنية. استشر دائمًا متخصصًا طبيًا مؤهلًا للحصول على التشخيص والعلاج.',
  },
};

export async function generatePDFReport(data: ReportData) {
  const t = translations[data.language as keyof typeof translations] || translations.en;

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  let yPosition = 20;
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const maxWidth = pageWidth - margin * 2;

  // Helper function to add text with automatic line breaking and page breaks
  const addText = (
    text: string,
    fontSize: number,
    isBold: boolean = false,
    yOffset: number = 5
  ) => {
    doc.setFontSize(fontSize);
    doc.setFont('Helvetica', isBold ? 'bold' : 'normal');

    const lines = doc.splitTextToSize(text, maxWidth);
    lines.forEach((line: string) => {
      if (yPosition > pageHeight - 20) {
        doc.addPage();
        yPosition = 20;
      }
      doc.text(line, margin, yPosition);
      yPosition += yOffset;
    });
  };

  // Title
  addText(t.title, 18, true, 8);
  yPosition += 3;

  // Generated date
  addText(
    `${t.generatedOn}: ${new Date().toLocaleString()}`,
    10,
    false,
    6
  );
  yPosition += 5;

  // Patient Information Section
  addText(t.patientInfo, 14, true, 7);
  yPosition += 1;

  const patientDetails = [
    `${t.age}: ${data.patientInfo?.age || t.notProvided}`,
    `${t.gender}: ${data.patientInfo?.gender || t.notProvided}`,
    `${t.allergies}: ${data.patientInfo?.allergies || t.notProvided}`,
    `${t.chronicConditions}: ${data.patientInfo?.chronicConditions || t.notProvided}`,
  ];

  patientDetails.forEach((detail) => {
    addText(detail, 10, false, 5);
  });
  yPosition += 4;

  // Symptom Description Section
  addText(t.symptomDescription, 14, true, 7);
  yPosition += 1;
  addText(data.symptomDescription, 10, false, 5);
  yPosition += 4;

  // Analysis Results Section
  addText(t.analysisResults, 14, true, 7);
  yPosition += 1;

  // Possible Condition
  addText(`${t.possibleCondition}:`, 11, true, 6);
  addText(data.analysis.possibleCondition, 10, false, 5);
  yPosition += 2;

  // Severity
  addText(`${t.severity}:`, 11, true, 6);
  addText(data.analysis.severity.toUpperCase(), 10, false, 5);
  yPosition += 2;

  // Extracted Symptoms
  addText(`${t.symptomsExtracted}:`, 11, true, 6);
  yPosition += 1;
  data.analysis.symptomsExtracted.forEach((symptom) => {
    addText(`• ${symptom}`, 10, false, 5);
  });
  yPosition += 2;

  // Feeling Summary
  addText(`${t.feelingSummary}:`, 11, true, 6);
  addText(data.analysis.feelingSummary, 10, false, 5);
  yPosition += 2;

  // Self-Care Tips
  addText(`${t.selfCareTips}:`, 11, true, 6);
  addText(data.analysis.selfCareTips, 10, false, 5);
  yPosition += 2;

  // Recommended Doctor
  addText(`${t.recommendedDoctor}:`, 11, true, 6);
  addText(data.analysis.recommendedDoctor, 10, false, 5);
  yPosition += 2;

  // Next Steps
  addText(`${t.nextSteps}:`, 11, true, 6);
  yPosition += 1;
  data.analysis.nextSteps.forEach((step) => {
    addText(`• ${step}`, 10, false, 5);
  });
  yPosition += 2;

  // Additional Notes
  addText(`${t.additionalNotes}:`, 11, true, 6);
  addText(data.analysis.additionalNotes, 10, false, 5);
  yPosition += 4;

  // Disclaimer
  addText(t.disclaimer, 8, true, 4);

  // Save the PDF
  const filename = `symptom_report_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
}
